version: '3.8'

services:
  db:
    image: postgres:16
    container_name: financial-db
    environment:
      - POSTGRES_DB=financial
      - POSTGRES_USER=financial
      - POSTGRES_PASSWORD=financial
    ports:
      - "5432:5432"
    networks:
      - financial-network

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    networks:
      - financial-network

networks:
  financial-network:
    driver: bridge
