version: '3.8'

services:
  db:
    image: postgres:16
    container_name: financial-db
    environment:
      - POSTGRES_DB=financial
      - POSTGRES_USER=financial
      - POSTGRES_PASSWORD=financial
    ports:
      - "5432:5432"
    networks:
      - financial-network

networks:
  financial-network:
    driver: bridge
